<body>
    <main>
        <article class="admin-container-tool">
            <h2>Herramientas</h2>
            <div>
                <a href="<?php echo BASE_URL; ?>/admin/add">Agregar Producto</a>
                <div class="admin-add-category">
                    <button class="add-category">Agegar Categoria</button>
                    <form action="<?php echo BASE_URL; ?>/addBrand" method="POST" class="form-add-category hidden">
                        <label for="new-brand">Nueva Categoria</label>
                        <input name="new-brand" type="text">
                        <div>
                            <button type="submit">Crear</button>
                            <button class="cancel-category" type="button">Cancelar</button>
                        </div>
                    </form>
                </div>
                <div class="admin-container-delete">

                    <button class="delete-category">Borrar Categoria</button>

                    <form class="form-delete-category hidden" action="<?php echo BASE_URL; ?>/deleteBrand" method="POST">

                        <div>
                            <select name="delete-brand">
                                <?php foreach ($arrBrand as $brand => $count): ?>
                                    <option value="<?= $count == 0 ? $brand : "invalido" ?>"><?= $brand ?> (<?= $count ?> productos)</option>
                                <?php endforeach; ?>
                            </select>
                            <button class="button-delete" type="submit">borrar</button>
                            <button type="button" class="cancel-delete-category">cancelar</button>
                        </div>


                        <p><svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                <g id="SVGRepo_iconCarrier">
                                    <path d="M12 7.01001V7.00002M12 17L12 10M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="#8d8d8d99" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                            </svg>Solo podes borrar si el producto no tiene categoria</p>

                    </form>

                </div>
            </div>
        </article>
        <article class="admin-container-product">
            <?php foreach ($product as $element): ?>
                <a href="<?php echo BASE_URL; ?>/edit/<?= $element->id ?>" class="product-card">

                    <img class="product-card-img" src="<?= $element->img ?>" alt="img_product_example">

                    <div class="card-body">

                        <h3><?= $element->name ?></h3>

                        <p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum
                            ha sid</p>

                        <p>stock: <span
                                class="<?= $element->stock == 1 ? "stock" : "no-stock" ?>"><?= $element->stock == 1 ? "disponible" : "no disponible" ?></span>
                        </p>
                        <div class="card-price">
                            <div class="card-offer">
                                <span class="<?= $element->offer > 0 ? "offert" : "" ?>"><?= $element->price ?></span><span
                                    class="<?= $element->offer_price == 0 ? "hidden" : "" ?>"> <?= $element->offer ?>%
                                    <?= $element->offer_price ?></span>
                            </div>
                            <p class="quota">
                                <?php
                                switch ($element->quota) {
                                    case 0:
                                        break;
                                    case 6:
                                        echo "6 Cuotas sin interés";
                                        break;
                                    case 12:
                                        echo "12 Cuotas sin interés";
                                        break;
                                    case 612:
                                        echo "6 y 12 Cuotas sin interés";
                                        break;
                                }
                                ?>
                            </p>
                        </div>
                    </div>
                </a>
            <?php endforeach ?>
        </article>
    </main>
   
    <?php require 'components/footer.phtml'; ?>
   
</body>

</html>