<body>
    <main class="category-main">
        <form id="category-form" action="<?php echo BASE_URL ?>/category" method="POST">
            <div class="category-form-element">
                <h1>Cateogrias</h1>
                <?php foreach ($category as $index => $brand): ?>
                    <div>
                        <label for="brand-<?= $index ?>"><?= $brand->brand ?></label>
                        <input type="radio" id="brand-<?= $index ?>" class="category-radio" name="brand"
                            value="<?= $brand->brand ?>">
                    </div>
                <?php endforeach; ?>
                <div>
                    <label for="brand-all">Todos</label>
                    <input id="brand-all" class="category-radio" type="radio" name="brand" value="all">
                </div>
                <button type="submit">Filtrar</button>
            </div>
            
        </form>
        <article class="category-product">
            <?php foreach ($product as $element): ?>
                <?php require 'components/card.phtml' ?>
            <?php endforeach ?>
        </article>
    </main>
    <?php require 'components/footer.phtml'; ?>
</body>

</html>