<html>

<?php require_once 'components/nav.phtml' ?>
<body>
    <?php foreach ($product as $element): ?>
        <main class="detail-main">
            <a class="detail-back-link" href="<?php echo BASE_URL ?>/category ?>"><- Volver</a>
                    <section class="detail-container">
                        <img src="<?= $element->img ?>" width="600px" alt="">
                        <article class="detail-article">
                            <h4><?= $element->brand ?></h4>
                            <h1><?= $element->name ?></h1>
                            <p><?= $element->description ?></p>
                            </div>
                            <div class="container-specifications">
                                <h6>Especificaciones</h6>
                                <ul>
                                    <li>Sistema <?= $element->system ?> </li>
                                    <li>Pantalla <?= $element->screen ?> </li>
                                    <li>Camara <?= $element->camera ?> mp</li>
                                    <li>Gama <?php
                                                switch ($element->gamma) {
                                                    case 'low':
                                                        echo "Baja";
                                                        break;
                                                    case 'medium':
                                                        echo "Media";
                                                        break;
                                                    case 'high':
                                                        echo "Alta";
                                                        break;
                                                    default:
                                                        echo "no coincide con alguno";
                                                        break;
                                                }
                                                ?></li>
                                </ul>
                            </div>
                            <div class="container-price">
                                <h6>Metodo de pago</h6>

                                <ul class="container-detail-price">
                                    <li> Stock <span
                                            class="<?= $element->stock == 1 ? "stock" : "no-stock" ?>"><?= $element->stock == 1 ? "disponible" : "no disponible" ?></span>
                                    </li>
                                    <li>Cuotas sin interés
                                        <?php
                                        switch ($element->quota) {
                                            case 0:
                                                echo "No";
                                                break;
                                            case 6:
                                                echo "6 Cuotas";
                                                break;
                                            case 12:
                                                echo "12 Cuotas";
                                                break;
                                            default:
                                                echo "no coincide con alguno";
                                                break;
                                        }
                                        ?>

                                    </li>
                                    <li>Precio <span class="<?= $element->offer > 0 ? "offert" : "" ?>"><?= $element->price ?></span><span
                                            class="<?= $element->offer_price == 0 ? "hidden" : "" ?>"> <?= $element->offer ?>%
                                            <?= $element->offer_price ?></span></li>
                                </ul>

                            </div>
                            <div class="container-add-product">
                                <a href="<?php echo BASE_URL ?>/buy/<?= $element->id ?>">Comprar</a>
                                <div class="container-info"><svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                        <g id="SVGRepo_iconCarrier">
                                            <path d="M12 7.01001V7.00002M12 17L12 10M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="#8d8d8d99" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                        </g>
                                    </svg>
                                    <p class="text-info"> Debe estar registrado para poder realizar una compra</p>
                                </div>
                            </div>
                        </article>
                    <?php endforeach ?>

                    </section>

        </main>
        <?php require 'components/footer.phtml'; ?>
</body>

</html>