<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css">
    <title>Tienda de Celulares</title>
</head>
<body>



<h1><?= $status ?></h1>
<p><?= $error ?></p>
<a href="<?php echo BASE_URL ?>/<?php echo $backToUrl ?>">Volver a <?= $backTo ?></a>
</body>

</html>