<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css">
    <title>Tienda de Celulares</title>
</head>

<body>
    <main class="login-main">
        <a href="<?php echo BASE_URL ?>/"><svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                <g id="SVGRepo_iconCarrier">
                    <g clip-path="url(#clip0_15_3)">
                        <rect width="24" height="24" fill="white"></rect>
                        <path d="M9 21H4C3.44772 21 3 20.5523 3 20V12.4142C3 12.149 3.10536 11.8946 3.29289 11.7071L11.2929 3.70711C11.6834 3.31658 12.3166 3.31658 12.7071 3.70711L20.7071 11.7071C20.8946 11.8946 21 12.149 21 12.4142V20C21 20.5523 20.5523 21 20 21H15M9 21H15M9 21V15C9 14.4477 9.44772 14 10 14H14C14.5523 14 15 14.4477 15 15V21" stroke="#000000" stroke-linejoin="round"></path>
                    </g>
                    <defs>
                        <clipPath id="clip0_15_3">
                            <rect width="24" height="24" fill="white"></rect>
                        </clipPath>
                    </defs>
                </g>
            </svg>Home</a>
        <form class="form-login" action="<?php echo BASE_URL ?>/login" method="POST">
            <img src="https://cdn-icons-png.flaticon.com/512/3736/3736502.png" alt="img_user">
            <div class="login-body">
                <div>
                    <label for="user">Usuario</label>
                    <input type="user" name="user" required>
                </div>
                <div>
                    <label for="password">Contraseña</label>
                    <input required type="password" name="password">
                </div>
                <div>
                    <button type="submit">Iniciar Sesion</button>
                    <p>o</p>
                    <a href="<?php echo BASE_URL ?>/showRegister">Registrarse</a>
                </div>
            </div>
        </form>
    </main>
</body>

</html>