<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css">
    <title>Tienda de Celulares</title>
</head>

<body>
    <main class="login-main">
        <form class="form-login" action="<?php echo BASE_URL ?>/login" method="POST">
            <img src="https://cdn-icons-png.flaticon.com/512/3736/3736502.png" alt="img_user">
            <div class="login-body">
                <div>
                    <label for="user">Usuario</label>
                    <input type="user" name="user" require>
                </div>
                <div>
                    <label for="password">Contraseña</label>
                    <input type="password" name="password">
                </div>
                <div>
                    <button type="submit">Iniciar Sesion</button>
                    <p>o</p>
                    <a href="">Registrarse</a>
                </div>
            </div>
        </form>
    </main>
</body>

</html>