<html lang="en">

<?php require 'components/head.phtml'; ?>

<body>




    <main>
        <form action="addProduct" method="POST">

                <input type="text">

                


        </form>

        <article class="home-product">
            <?php foreach ($product as $element): ?>

                    <div></div>

                <?php endforeach ?>
        </article>

    </main>

    <?php require 'components/footer.phtml'; ?>

</body>

</html>