<html lang="en">

<?php require 'components/head.phtml'; ?>

<body>
        <?php require 'components/nav.phtml' ?>

        <article class="home-product">
            <?php foreach ($product as $element): ?>

                <div>

                    <h3><?= $element->name ?></h3>

                    <p><?= $element->description ?></p>

                    <span><?= $element->price ?></span>

                    <a href="<?php echo BASE_URL; ?>/detail/<?= $element->id ?>">Detalles</a>
                </div>

            <?php endforeach ?>
        </article>

    </main>

    <?php require 'components/footer.phtml'; ?>

</body>

</html>