<html lang="en">

<?php require 'components/head.phtml'; ?>

<body>

    <?php require 'components/nav.phtml'; ?>


    <main>
        <form action="<?php echo BASE_URL; ?>/filter" method="POST">

            <div><label for="min_price">Min</label>
                <input type="text" value="<?= $minPrice !== null ? $minPrice : '0'; ?>" name="min_price">
            </div>
            <div><label for="max_price">Max</label>
                <input type="text" value="<?= $maxPrice !== null ? $maxPrice : '0'; ?>" name="max_price">
            </div>
            <div>
                <label for="brand">Marca</label>
                <select name="brand">
                    <option value="">---</option>
                    <option value="Apple">Apple</option>
                    <option value="Samsung">Samsung</option>
                    <option value="Google">Google</option>
                    <option value="OnePlus">OnePlus</option>
                    <option value="Xiaomi">Xiaomi</option>
                    <option value="Sony">Sony</option>
                    <option value="Huawei">Huawei</option>
                    <option value="Oppo">Oppo</option>
                    <option value="Motorola">Motorola</option>
                    <option value="Nokia">Nokia</option>
                </select>
            </div>


            <button type="submit">Filtrar</button>

        </form>

        <article class="home-product">
            <?php foreach ($product as $element): ?>

                <div class="card">

                    <h3><?= $element->name ?></h3>

                    <p><?= $element->description ?></p>

                    <span><?= $element->price ?></span>

                    <a href="<?php echo BASE_URL; ?>/detail/<?= $element->id ?>">Detalles</a>
                </div>

            <?php endforeach ?>
        </article>

    </main>

    <?php require 'components/footer.phtml'; ?>

</body>

</html>