<html>



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>">
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css">
    <title>Tienda de Celulares</title>
</head>

<body>
    <main class="register-main">   
        <form class="form-register" action="<?php echo BASE_URL ?>/register" method="POST">
            <h1>Registro</h1>
            <div class="form-register-img">
                <img src="https://cdn-icons-png.flaticon.com/512/3736/3736502.png" alt="user_img">
                <div>
                    <h2>Foto de Perfil</h2>
                    <input name="img-profile" type="text">
                    <p>(opcional) carga una url de una imagen de internet </p>
                </div>
            </div>

            <div>
                <label for="user-name">Nombre de Usuario</label>
                <input required name="user-name" type="text">
            </div>
            <div>
                <label for="email">Email</label>
                <input name="email" type="email">
            </div>

            <div>
                <label for="password">Contraseña</label>
                <input required name="password" type="password">
            </div>

            <div>
                <label for="confirm-password">Confirmar Contraseña</label>
                <input required name="confirm-password" type="password">
            </div>

            <div>
                <button type="submit">Registrarme</button>
                <a href="<?php echo BASE_URL ?>/showLogin">Cancelar</a>
            </div>

        </form>
    </main>
</body>

</html>