<nav>



    <ul>

        <li><a href="<?php echo BASE_URL; ?>/">Inicio</a></li>


        <li id="atr">
            <a href="<?php echo BASE_URL; ?>/phone">Celulares</a>
            <div id="fede" class="hidden">
                <?php foreach($brand as $element): ?>
                    <a href="<?php echo BASE_URL; ?>/phone/<?php echo $element->brand ?>"><?= $element->brand ?></a>
                <?php endforeach; ?>
            </div>

        </li>

        <li><a href="<?php echo BASE_URL; ?>/admin">admin</a>
        </li>
    </ul>


</nav>